# Gunakan image Node.js sebagai dasar
FROM node:18

# Buat direktori kerja di dalam container
WORKDIR /backend

# Salin package.json dan package-lock.json ke direktori kerja
COPY package*.json ./

# Install dependensi proyek
RUN npm install


# Salin seluruh file proyek ke direktori kerja
COPY . .

# Install Prisma Client
RUN npx prisma generate

# Port yang digunakan oleh aplikasi backend
EXPOSE 7171

# Perintah untuk menjalankan aplikasi Express
CMD [ "npm", "run", "start" ]
