//////////////////////// CRUD USER ////////////////////////////
###
GET https://api-spendwise.agilearn.id/users

###
POST https://api-spendwise.agilearn.id/users
Content-Type: application/json

{   
    "full_name": "Reza Ananta",
    "username": "rezaanta",
    "password": "ananta229",
    "confirmPassword": "ananta229"
}

###
PATCH https://api-spendwise.agilearn.id/users/junet
Content-Type: application/json

{
    "password": "12345"
}

###
DELETE https://api-spendwise.agilearn.id/users/junet


### Login
POST https://api-spendwise.agilearn.id/login
Content-Type: application/json

{
    "username": "rvldfr",
    "password": "12345"
}

//////////////////////// CRUD WALLET ////////////////////////////

###
GET https://api-spendwise.agilearn.id/wallets/rvldfr

###
POST https://api-spendwise.agilearn.id/wallets
Content-Type: application/json

{
    "name": "BCA",
    "balance": 2000000,
    "user_id": 1
}

###
DELETE https://api-spendwise.agilearn.id/wallets/ferdy/BRI


###
PATCH https://api-spendwise.agilearn.id/wallets/junet/GOPAY
Content-Type: application/json

{
    "balance": 75000000
}

//////////////////////// CRUD CATEGORY ////////////////////////////
###
GET https://api-spendwise.agilearn.id/categories/ferdy

###
POST https://api-spendwise.agilearn.id/categories
Content-Type: application/json

{
    "name": "Hiburan",
    "user_id": 1
}

###
PATCH https://api-spendwise.agilearn.id/categories/ferdy/Hiburan
Content-Type: application/json

{
    "name": "Makanan"
}

###
DELETE https://api-spendwise.agilearn.id/categories/ferdy/Hiburan

//////////////////////// CRUD INCOMES ////////////////////////////
###
GET  https://api-spendwise.agilearn.id/incomes/rvldfr

###
POST https://api-spendwise.agilearn.id/incomes
Content-Type: application/json

{
    "title": "Bonus",
    "amount": 50000,
    "description": "rezeki nich",
    "date": "2023-12-06T00:00:00Z",
    "wallet_id": 1
}


###
GET  https://api-spendwise.agilearn.id/incomes-period/junet?startDate=2023-11-14&endDate=2023-11-15


###
DELETE https://api-spendwise.agilearn.id/incomes/junet/2

//////////////////////// CRUD BUDGET ////////////////////////////
###
GET  https://api-spendwise.agilearn.id/budgets/rezaanta

###
GET  https://api-spendwise.agilearn.id/budgets/ferdy/Transport

###
POST https://api-spendwise.agilearn.id/budgets
Content-Type: application/json

{
    "title": "A",
    "amount": 550000,
    "date": "2023-11-25T09:30:00Z",
    "category_id": 7
}

###
PATCH  https://api-spendwise.agilearn.id/budgets/ferdy/1
Content-Type: application/json

{
    "amount_now": 150000
}

###
DELETE https://api-spendwise.agilearn.id/budgets/ferdy/11

//////////////////////// CRUD EXPENSE ////////////////////////////
###
GET  https://api-spendwise.agilearn.id/expenses/ferdy

###
POST https://api-spendwise.agilearn.id/expenses
Content-Type: application/json

{
    "title": "Servis Motor Beat",
    "amount": 350000,
    "description": "servis cvt, ganti oli, ganti rem lampu",
    "date": "2023-11-25T09:30:00Z",
    "wallet_id": 1,
    "budget_id": 6
}

###
PATCH https://api-spendwise.agilearn.id/expenses/junet/3
Content-Type: application/json

{
    "amount": 35000
}

###
DELETE  https://api-spendwise.agilearn.id/expenses/junet/4