//////////////////////// CRUD USER ////////////////////////////
###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{   
    "full_name": "Reza Ananta",
    "username": "rezaanta",
    "password": "ananta229",
    "confirmPassword": "ananta229"
}

###
PATCH http://localhost:5000/users/junet
Content-Type: application/json

{
    "password": "12345"
}

###
DELETE http://localhost:5000/users/gian


### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "rvldfr",
    "password": "12345"
}

//////////////////////// CRUD WALLET ////////////////////////////

###
GET http://localhost:5000/wallets/rvldfr

###
POST http://localhost:5000/wallets
Content-Type: application/json

{
    "name": "BCA",
    "balance": 2000000,
    "user_id": 1
}

###
DELETE http://localhost:5000/wallets/ferdy/BRI


###
PATCH http://localhost:5000/wallets/junet/GOPAY
Content-Type: application/json

{
    "balance": 75000000
}

//////////////////////// CRUD CATEGORY ////////////////////////////
###
GET http://localhost:5000/categories/ferdy

###
POST http://localhost:5000/categories
Content-Type: application/json

{
    "name": "Hiburan",
    "user_id": 1
}

###
PATCH http://localhost:5000/categories/ferdy/Hiburan
Content-Type: application/json

{
    "name": "Makanan"
}

###
DELETE http://localhost:5000/categories/ferdy/Hiburan

//////////////////////// CRUD INCOMES ////////////////////////////
###
GET  http://localhost:5000/incomes/rvldfr

###
POST http://localhost:5000/incomes
Content-Type: application/json

{
    "title": "Bonus",
    "amount": 20000,
    "description": "rezeki nich",
    "date": "2023-11-14T09:30:00Z",
    "wallet_id": 2
}


###
GET  http://localhost:5000/incomes-period/junet?startDate=2023-11-14&endDate=2023-11-15


###
DELETE http://localhost:5000/incomes/junet/2

//////////////////////// CRUD BUDGET ////////////////////////////
###
GET  http://localhost:5000/budgets/rezaanta

###
GET  http://localhost:5000/budgets/ferdy/Transport

###
POST http://localhost:5000/budgets
Content-Type: application/json

{
    "title": "A",
    "amount": 550000,
    "date": "2023-11-25T09:30:00Z",
    "category_id": 7
}

###
PATCH  http://localhost:5000/budgets/ferdy/1
Content-Type: application/json

{
    "amount_now": 150000
}

###
DELETE http://localhost:5000/budgets/ferdy/11

//////////////////////// CRUD EXPENSE ////////////////////////////
###
GET  http://localhost:5000/expenses/rvldfr

###
POST http://localhost:5000/expenses
Content-Type: application/json

{
    "title": "Servis Motor Beat",
    "amount": 350000,
    "description": "servis cvt, ganti oli, ganti rem lampu",
    "date": "2023-11-25T09:30:00Z",
    "wallet_id": 1,
    "budget_id": 6
}

###
PATCH http://localhost:5000/expenses/junet/3
Content-Type: application/json

{
    "amount": 35000
}

###
DELETE  http://localhost:5000/expenses/junet/4